### ISSUE TITLE
关于数据爬取的问题？

### ISSUE THREAD

**Issue by zhu327** [fuermosi777/studentdaily#1]
不懂object-C，但是我有自己写过python的，从搜狗爬取数据

请问你是从搜狗爬的吗？
我碰到搜狗的反爬虫，请教你下针对搜狗的反爬虫做的措施

**Comment by fuermosi777** [comment]
是从搜狗爬的，主要就是换不同代理反爬。不过效果不是很好。

**Comment by zhu327** [comment]
自己研究了下，搜狗应该是通过cookie来反爬的，通过代理发HEAD请求，保存cookie，维护一个cookie池，爬的时候随机从cookie池中取cookie。还没有实现，只是想法，另外靠谱代理那里找？

**Comment by fuermosi777** [comment]
有个hidemyass代理蛮多的。。。

**Comment by zhu327** [comment]
hidemyass 名字好屌...
